[package]
name = "ataxia_types"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
enumflags2 = { version = "0.7.12", features = ["serde"] }
rand = "0.10.0"
regex = "1.12.3"
schemars = { version = "1.2.1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = {version = "1.0.149", optional = true }
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.19"

rhai = {version = "1.25.1", optional = true }

[features]
serde = ["dep:serde", "dep:serde_json"]
schema = ["dep:schemars"]
rhai = ["dep:rhai"]
