[package]
name = "ataxia_scripting"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ataxia_types = { workspace = true, features = ["schema", "serde", "rhai"] }
anyhow = { workspace = true }
rhai = { workspace = true, features = ["sync"] }
rand.workspace = true
regex = "1.13.1"
