[package]
name = "ataxia"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
ataxia_types = {path = "../ataxia_types", features = ["schema", "serde"]}
iced = {version = "0.14.0", features = ["tokio"]}
serde = { version = "1.0.229" }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }

[clippy.lints]
pedantic = {level = "deny" }
nursery = {level = "deny" }
