[package]
name = "serenity_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["lazy" ] }
log = "0.4.29"
rfd = "0.17.2"
serde = "1.0.228"
serde_json = "1.0.149"
serenity_types = { path = "../serenity_types" }

[features]
debug = ["iced/hot"]


[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
